# Generated by Django 3.2.2 on 2021-06-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeinfo',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
