# Generated by Django 3.2.2 on 2021-06-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_employeeinfo_mname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
